<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>quantum</string>
		<string>um</string>
	</array>
	<key>name</key>
	<string>Quantum</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(@{1,2}js)\s*$|(@{1,2}codeblock) (js)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-js.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}json)\s*$|(@{1,2}codeblock) (json)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-json.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}html)\s*$|(@{1,2}codeblock) (html)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-html.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}xml)\s*$|(@{1,2}codeblock) (xml)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-xml.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}coffee)\s*$|(@{1,2}codeblock) (coffee)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-coffee.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.coffee</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}python)\s*$|(@{1,2}codeblock) (python)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-python.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}csharp)\s*$|(@{1,2}codeblock) (csharp)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-csharp.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}scala)\s*$|(@{1,2}codeblock) (scala)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-scala.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.scala</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}java)\s*$|(@{1,2}codeblock) (java)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-java.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}css)\s*$|(@{1,2}codeblock) (css)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-css.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\t</string>
			<key>name</key>
			<string>invalid.illegal.um</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@@@+</string>
			<key>name</key>
			<string>invalid.illegal.um</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*#</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.um</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}[^\[\(: ]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.um</string>
			<key>end</key>
			<string>(:|$|(?&lt;=[\)\]]) [^\[])|\n</string>
			<key>name</key>
			<string>meta.quantum.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]{1,2}</string>
					<key>name</key>
					<string>string.um</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.um</string>
</dict>
</plist>
