<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>quantum</string>
		<string>um</string>
	</array>
	<key>name</key>
	<string>Quantum</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(@js)\s*$|(@codeblock) (js)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-js.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@json)\s*$|(@codeblock) (json)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-json.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@html)\s*$|(@codeblock) (html)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-html.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@css)\s*$|(@codeblock) (css)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-css.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@[^\[\(: ]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.um</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.um</string>
			<key>end</key>
			<string>(:|$|(?&lt;=[\)\]]) [^\[])|\n</string>
			<key>name</key>
			<string>meta.quantum.um</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>variable.parameter.um</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>string.um</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\t</string>
			<key>name</key>
			<string>invalid.illegal.um</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.um</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.um</string>
</dict>
</plist>
