'use strict'
require('chai').should()
require('./module.spec')
require('./config.spec')
require('./languages/index.spec')
require('./transforms.spec')
require('./fileTransform.spec')
require('./file-transforms/changelog.spec.js')
require('./entity-transforms/index.spec.js')
require('./utils.spec')
