'use strict'
global.Promise = require('bluebird')
const chai = require('chai')
const chaiAsPromised = require('chai-as-promised')
chai.use(chaiAsPromised)
chai.should()
require('./module.spec')
require('./asset.spec')
require('./bodyClassed.spec')
require('./create.spec')
require('./Element.spec')
require('./escapeHTML.spec')
require('./head.spec')
require('./randomId.spec')
require('./stringify.spec')
require('./textNode.spec')
