'use strict'
const chai = require('chai')
const chaiAsPromised = require('chai-as-promised')
chai.use(chaiAsPromised)
chai.should()
require('./module.spec')
require('./clone.spec')
require('./File.spec')
require('./FileInfo.spec')
require('./fileOptions.spec')
require('./json.spec')
require('./parse.spec')
require('./read.spec')
require('./select.spec')
require('./stringify.spec')
require('./watch.spec')
require('./write.spec')
