<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>quantum</string>
		<string>um</string>
	</array>
	<key>name</key>
	<string>Quantum</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(@{1,2}js)\s*$|(@{1,2}codeblock) (js)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.quantum</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-js.quantum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}json)\s*$|(@{1,2}codeblock) (json)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.quantum</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-json.quantum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}html)\s*$|(@{1,2}codeblock) (html)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.quantum</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-html.quantum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}xml)\s*$|(@{1,2}codeblock) (xml)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.quantum</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-xml.quantum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}coffee)\s*$|(@{1,2}codeblock) (coffee)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.quantum</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-coffee.quantum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.coffee</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}python)\s*$|(@{1,2}codeblock) (python)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.quantum</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-python.quantum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}csharp)\s*$|(@{1,2}codeblock) (csharp)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.quantum</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-csharp.quantum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}scala)\s*$|(@{1,2}codeblock) (scala)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.quantum</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-scala.quantum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.scala</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}java)\s*$|(@{1,2}codeblock) (java)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.quantum</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-java.quantum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}css)\s*$|(@{1,2}codeblock) (css)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.quantum</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-css.quantum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}scss)\s*$|(@{1,2}codeblock) (scss)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.quantum</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-scss.quantum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sass</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}markdown)\s*$|(@{1,2}codeblock) (markdown)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.quantum</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=@)</string>
			<key>name</key>
			<string>meta.quantum.embedded-markdown.quantum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.markdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\t</string>
			<key>name</key>
			<string>invalid.illegal.quantum</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@@@+</string>
			<key>name</key>
			<string>invalid.illegal.quantum</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*#</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.quantum</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@{1,2}[^\[\(: ]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.quantum</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.quantum</string>
			<key>end</key>
			<string>(:|$|(?&lt;=[\)\]])[ ,.][^\[])|\n</string>
			<key>name</key>
			<string>meta.quantum.quantum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>variable.parameter.quantum</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]{1,2}</string>
					<key>name</key>
					<string>string.quantum</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.quantum</string>
	<key>uuid</key>
	<string>18c5274f-0ee9-4e9c-82fd-285061644134</string>
</dict>
</plist>
