#! /bin/bash

# This script removes all the node_modules folders

pushd ..

pushd quantum-js
rm -r node_modules
popd

pushd quantum-dom
rm -r node_modules
popd

pushd quantum-html
rm -r node_modules
popd

pushd quantum-api
rm -r node_modules
popd

pushd quantum-changelog
rm -r node_modules
popd

pushd quantum-diagram
rm -r node_modules
popd

pushd quantum-docs
rm -r node_modules
popd

pushd quantum-version
rm -r node_modules
popd

pushd quantum-watch
rm -r node_modules
popd


popd