#! /bin/bash

# This script removes all the node_modules folders

rm -rf quantum-js/node_modules
rm -rf quantum-dom/node_modules
rm -rf quantum-html/node_modules
rm -rf quantum-api/node_modules
rm -rf quantum-changelog/node_modules
rm -rf quantum-diagram/node_modules
rm -rf quantum-docs/node_modules
rm -rf quantum-version/node_modules
rm -rf quantum-watch/node_modules
rm -rf quantum-template/node_modules
rm -rf quantum-hub/node_modules
rm -rf quantum-cli/node_modules
rm -rf docs/node_modules
rm -rf docs/target
