#! /bin/bash

# This script is useful for developing locally - it will npm link all the modules

pushd quantum-js
npm link
npm install
popd

pushd quantum-dom
npm link
npm install
popd

pushd quantum-template
npm link quantum-js
npm install
npm link
popd

pushd quantum-html
npm link quantum-js quantum-dom
npm install
npm link
popd

pushd quantum-code-highlight
npm link quantum-js
npm install
npm link
popd

pushd quantum-api
npm link quantum-js
npm install
npm link
popd

pushd quantum-changelog
npm link quantum-js
npm install
npm link
popd

pushd quantum-diagram
npm link quantum-js
npm install
npm link
popd

pushd quantum-docs
npm link quantum-js quantum-html
npm install
npm link
popd

pushd quantum-version
npm link quantum-js
npm install
npm link
popd

pushd docs
npm link quantum-js quantum-html quantum-template quantum-api quantum-changelog quantum-diagram quantum-docs quantum-version quantum-code-highlight
npm install
popd
