#! /bin/bash

# This script is useful for developing locally - it will npm link all the modules

pushd quantum-core
npm install
npm link
popd

pushd quantum-dom
npm install
npm link
popd

pushd quantum-template
npm link quantum-core
npm install
npm link
popd

pushd quantum-html
npm link quantum-core quantum-dom
npm install
npm link
popd

pushd quantum-code-highlight
npm link quantum-core quantum-dom
npm install
npm link
popd

pushd quantum-api
npm link quantum-core quantum-dom quantum-html quantum-version
npm install
npm link
popd

pushd quantum-diagram
npm link quantum-core quantum-dom
npm install
npm link
popd

pushd quantum-docs
npm link quantum-core quantum-html quantum-dom
npm install
npm link
popd

pushd quantum-version
npm link quantum-core
npm install
npm link
popd

pushd quantum-markdown
npm link quantum-core quantum-dom quantum-code-highlight
npm install
npm link
popd

pushd docs
npm link quantum-core quantum-html quantum-template quantum-api quantum-diagram quantum-dom quantum-docs quantum-version quantum-code-highlight quantum-markdown
npm install
popd
