#! /bin/bash

# This script does the reverse of link - it will npm unlink everything
# that was linked by the link script

pushd quantum-js
npm unlink
popd

pushd quantum-dom
npm unlink
popd

pushd quantum-template
npm unlink quantum-js
npm unlink
popd

pushd quantum-html
npm unlink quantum-js quantum-dom
npm unlink
popd

pushd quantum-code-highlight
npm unlink quantum-js quantum-dom
npm unlink
popd

pushd quantum-api
npm unlink quantum-js quantum-dom quantum-html
npm unlink
popd

pushd quantum-changelog
npm unlink quantum-js quantum-dom quantum-html
npm unlink
popd

pushd quantum-diagram
npm unlink quantum-js quantum-dom
npm unlink
popd

pushd quantum-docs
npm unlink quantum-js quantum-html quantum-dom
npm unlink
popd

pushd quantum-version
npm unlink quantum-js
npm unlink
popd

pushd docs
npm unlink quantum-js quantum-html quantum-template quantum-api quantum-changelog quantum-diagram quantum-docs quantum-version quantum-code-highlight
popd
